### ISSUE TITLE
yapf breaks when parsing file with newline in string from stdin

### ISSUE THREAD

**Issue by pignacio** [google/yapf#79] opened 2015-04-08 19:20 UTC
Given a file `test.py` with contents

``` python
print '\n'
```

Formatting the file using the filename as argument works as expected:

```
% yapf test.py
print '\n'
```

But when reading the same file from stdin, yapf breaks

```
% yapf <test.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ignacio/src/yapf/yapf/__main__.py", line 16, in <module>
    yapf.run_main()
  File "/home/ignacio/src/yapf/yapf/__init__.py", line 189, in run_main
    sys.exit(main(sys.argv))
  File "/home/ignacio/src/yapf/yapf/__init__.py", line 119, in main
    verify=args.verify))
  File "/home/ignacio/src/yapf/yapf/yapflib/yapf_api.py", line 101, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/ignacio/src/yapf/yapf/yapflib/pytree_utils.py", line 100, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python2.7/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python2.7/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python2.7/lib2to3/pgen2/parse.py", line 116, in addtoken
    ilabel = self.classify(type, value, context)
  File "/usr/lib/python2.7/lib2to3/pgen2/parse.py", line 172, in classify
    raise ParseError("bad token", type, value, context)
lib2to3.pgen2.parse.ParseError: bad token: type=55, value=u' ', context=('', (1, 5))
```

The offending line seems to be `yapf/__init__.py:115`:

```
115         py3compat.unicode('\n'.join(original_source) + '\n'),
```

On python2 `py3compat.unicode(s)` calls `__builtin__.unicode(s, 'unicode_escape')`, which unescapes the string newline.

```
>>> __builtin__.unicode('"\\n"', 'unicode_escape')
u'"\n"'
>>> print _
"
"
>>> 
```

**Comment by gwelymernans** [comment] 2015-04-08 21:47
I think this is a duplicate of #70.

**Closed by gwelymernans** 2015-04-08 21:47 UTC
Labels: duplicate
