### ISSUE TITLE
yapf should add an option for different encodings。

### ISSUE THREAD

**Issue by lll9p** [google/yapf#90] opened 2015-04-13 02:26 UTC

**Comment by gwelymernans** [comment] 2015-04-17 03:25
Could you be a bit more specific? Is there an example which doesn't currently work?

**Comment by gpshead** [comment] 2015-04-17 23:31
duplicate of https://github.com/google/yapf/issues/49?

**Comment by gwelymernans** [comment] 2015-04-18 06:01
It sounds like it. Marking as dup of #49.

**Closed by gwelymernans** 2015-04-18 06:01 UTC
Labels: duplicate
